--MOEDAS

INSERT INTO MOEDA VALUES ('BRL', 0.20);
INSERT INTO MOEDA VALUES('USD', 1.00);
INSERT INTO MOEDA VALUES('EUR', 1.10);
INSERT INTO MOEDA VALUES('FRF', 0.80);
INSERT INTO MOEDA VALUES('JPY', 0.0075);
INSERT INTO MOEDA VALUES('GBP', 1.24);
INSERT INTO MOEDA VALUES('AUD', 0.67);
INSERT INTO MOEDA VALUES('CAD', 0.75);
INSERT INTO MOEDA VALUES('CHF', 1.12);
INSERT INTO MOEDA VALUES('EGP', 0.033); 
INSERT INTO MOEDA VALUES('CNY', 0.15);
INSERT INTO MOEDA VALUES('BTC', 30215);
INSERT INTO MOEDA VALUES('SOL', 24.33);
INSERT INTO MOEDA VALUES('DOG', 0.093);


--CRIPTOMOEDAS:


INSERT INTO CRIPTOMOEDA VALUES('BTC','xlr81sth3b3st');
INSERT INTO CRIPTOMOEDA VALUES('SOL', '3stud3g61');
INSERT INTO CRIPTOMOEDA VALUES('DOG', '3l0nmu5k');




--MOEDA FIDUCIARIA


INSERT INTO MOEDA_FIDUCIARIA VALUES ('BRL');
INSERT INTO MOEDA_FIDUCIARIA VALUES('USD');
INSERT INTO MOEDA_FIDUCIARIA VALUES('EUR');
INSERT INTO MOEDA_FIDUCIARIA VALUES('JPY');
INSERT INTO MOEDA_FIDUCIARIA VALUES('GBP');
INSERT INTO MOEDA_FIDUCIARIA VALUES('AUD');
INSERT INTO MOEDA_FIDUCIARIA VALUES('CAD');
INSERT INTO MOEDA_FIDUCIARIA VALUES('CHF');
INSERT INTO MOEDA_FIDUCIARIA VALUES('EGP');
INSERT INTO MOEDA_FIDUCIARIA VALUES('CNY');
INSERT INTO MOEDA_FIDUCIARIA VALUES('FRF');


--PAIS :
INSERT INTO PAIS VALUES('DE','ALEMANHA', 4260, 0,'EUR');
INSERT INTO PAIS VALUES('BR', 'BRASIL', 1609, 1, 'BRL');
INSERT INTO PAIS VALUES('AU', 'AUSTRÁLIA', 1495, 0, 'AUD');
INSERT INTO PAIS VALUES('CA', 'CANADA', 1766, 0, 'CAD');
INSERT INTO PAIS VALUES('CH', 'SUÍÇA', 703, 0, 'CHF');
INSERT INTO PAIS VALUES('FR', 'FRANÇA', 2958, 0, 'FRF');
INSERT INTO PAIS VALUES('UK', 'REINO UNIDO', 3089, 0, 'GBP');
INSERT INTO PAIS VALUES('JP', 'JAPÃO', 4870, 0, 'JPY');
INSERT INTO PAIS VALUES('US', 'ESTADOS UNIDOS', 21428, 0, 'USD');
INSERT INTO PAIS VALUES('EG', 'EGITO',  400, 0, 'EGP');
INSERT INTO PAIS VALUES('CN', 'CHINA' ,17730, 0, 'CNY');
--RECONHECE(reconhece, reconhecido)


INSERT INTO RECONHECE VALUES ('AU','BR');
INSERT INTO RECONHECE VALUES ('AU','CA');
INSERT INTO RECONHECE VALUES ('AU','CH');
INSERT INTO RECONHECE VALUES ('AU','CN');
INSERT INTO RECONHECE VALUES ('AU','DE');
INSERT INTO RECONHECE VALUES ('AU','EG');
INSERT INTO RECONHECE VALUES ('AU','FR');
INSERT INTO RECONHECE VALUES ('AU','JP');
INSERT INTO RECONHECE VALUES ('AU','UK');
INSERT INTO RECONHECE VALUES ('AU','US');
INSERT INTO RECONHECE VALUES ('BR','AU');
INSERT INTO RECONHECE VALUES ('BR','CA');
INSERT INTO RECONHECE VALUES ('BR','CH');
INSERT INTO RECONHECE VALUES ('BR','CN');
INSERT INTO RECONHECE VALUES ('BR','DE');
INSERT INTO RECONHECE VALUES ('BR','EG');
INSERT INTO RECONHECE VALUES ('BR','FR');
INSERT INTO RECONHECE VALUES ('BR','JP');
INSERT INTO RECONHECE VALUES ('BR','UK');
INSERT INTO RECONHECE VALUES ('BR','US');
INSERT INTO RECONHECE VALUES ('CA','AU');
INSERT INTO RECONHECE VALUES ('CA','BR');
INSERT INTO RECONHECE VALUES ('CA','CH');
INSERT INTO RECONHECE VALUES ('CA','CN');
INSERT INTO RECONHECE VALUES ('CA','DE');
INSERT INTO RECONHECE VALUES ('CA','EG');
INSERT INTO RECONHECE VALUES ('CA','FR');
INSERT INTO RECONHECE VALUES ('CA','JP');
INSERT INTO RECONHECE VALUES ('CA','UK');
INSERT INTO RECONHECE VALUES ('CA','US');
INSERT INTO RECONHECE VALUES ('CH','AU');
INSERT INTO RECONHECE VALUES ('CH','BR');
INSERT INTO RECONHECE VALUES ('CH','CA');
INSERT INTO RECONHECE VALUES ('CH','CN');
INSERT INTO RECONHECE VALUES ('CH','DE');
INSERT INTO RECONHECE VALUES ('CH','EG');
INSERT INTO RECONHECE VALUES ('CH','FR');
INSERT INTO RECONHECE VALUES ('CH','JP');
INSERT INTO RECONHECE VALUES ('CH','UK');
INSERT INTO RECONHECE VALUES ('CH','US');
INSERT INTO RECONHECE VALUES ('CN','AU');
INSERT INTO RECONHECE VALUES ('CN','BR');
INSERT INTO RECONHECE VALUES ('CN','CA');
INSERT INTO RECONHECE VALUES ('CN','CH');
INSERT INTO RECONHECE VALUES ('CN','DE');
INSERT INTO RECONHECE VALUES ('CN','EG');
INSERT INTO RECONHECE VALUES ('CN','FR');
INSERT INTO RECONHECE VALUES ('CN','JP');
INSERT INTO RECONHECE VALUES ('CN','UK');
INSERT INTO RECONHECE VALUES ('DE','AU');
INSERT INTO RECONHECE VALUES ('DE','BR');
INSERT INTO RECONHECE VALUES ('DE','CA');
INSERT INTO RECONHECE VALUES ('DE','CH');
INSERT INTO RECONHECE VALUES ('DE','CN');
INSERT INTO RECONHECE VALUES ('DE','EG');
INSERT INTO RECONHECE VALUES ('DE','FR');
INSERT INTO RECONHECE VALUES ('DE','JP');
INSERT INTO RECONHECE VALUES ('DE','UK');
INSERT INTO RECONHECE VALUES ('DE','US');
INSERT INTO RECONHECE VALUES ('EG','AU');
INSERT INTO RECONHECE VALUES ('EG','BR');
INSERT INTO RECONHECE VALUES ('EG','CA');
INSERT INTO RECONHECE VALUES ('EG','CH');
INSERT INTO RECONHECE VALUES ('EG','CN');
INSERT INTO RECONHECE VALUES ('EG','DE');
INSERT INTO RECONHECE VALUES ('EG','FR');
INSERT INTO RECONHECE VALUES ('EG','JP');
INSERT INTO RECONHECE VALUES ('EG','UK');
INSERT INTO RECONHECE VALUES ('EG','US');
INSERT INTO RECONHECE VALUES ('FR','AU');
INSERT INTO RECONHECE VALUES ('FR','BR');
INSERT INTO RECONHECE VALUES ('FR','CA');
INSERT INTO RECONHECE VALUES ('FR','CH');
INSERT INTO RECONHECE VALUES ('FR','CN');
INSERT INTO RECONHECE VALUES ('FR','DE');
INSERT INTO RECONHECE VALUES ('FR','EG');
INSERT INTO RECONHECE VALUES ('FR','JP');
INSERT INTO RECONHECE VALUES ('FR','UK');
INSERT INTO RECONHECE VALUES ('FR','US');
INSERT INTO RECONHECE VALUES ('JP','AU');
INSERT INTO RECONHECE VALUES ('JP','BR');
INSERT INTO RECONHECE VALUES ('JP','CA');
INSERT INTO RECONHECE VALUES ('JP','CH');
INSERT INTO RECONHECE VALUES ('JP','DE');
INSERT INTO RECONHECE VALUES ('JP','EG');
INSERT INTO RECONHECE VALUES ('JP','FR');
INSERT INTO RECONHECE VALUES ('JP','UK');
INSERT INTO RECONHECE VALUES ('JP','US');
INSERT INTO RECONHECE VALUES ('UK','AU');
INSERT INTO RECONHECE VALUES ('UK','BR');
INSERT INTO RECONHECE VALUES ('UK','CA');
INSERT INTO RECONHECE VALUES ('UK','CH');
INSERT INTO RECONHECE VALUES ('UK','CN');
INSERT INTO RECONHECE VALUES ('UK','DE');
INSERT INTO RECONHECE VALUES ('UK','EG');
INSERT INTO RECONHECE VALUES ('UK','FR');
INSERT INTO RECONHECE VALUES ('UK','JP');
INSERT INTO RECONHECE VALUES ('UK','US');
INSERT INTO RECONHECE VALUES ('US','AU');
INSERT INTO RECONHECE VALUES ('US','BR');
INSERT INTO RECONHECE VALUES ('US','CA');
INSERT INTO RECONHECE VALUES ('US','CH');
INSERT INTO RECONHECE VALUES ('US','DE');
INSERT INTO RECONHECE VALUES ('US','EG');
INSERT INTO RECONHECE VALUES ('US','FR');
INSERT INTO RECONHECE VALUES ('US','JP');
INSERT INTO RECONHECE VALUES ('US','UK');


________________


--AUSTRALIA
INSERT INTO CORES_BANDEIRA VALUES('Azul','AU');
INSERT INTO CORES_BANDEIRA VALUES('Branco','AU');
INSERT INTO CORES_BANDEIRA VALUES('Vermelho','AU');
--BRASIL
INSERT INTO CORES_BANDEIRA VALUES('Verde','BR');
INSERT INTO CORES_BANDEIRA VALUES('Amarelo','BR');
INSERT INTO CORES_BANDEIRA VALUES('Azul','BR');
INSERT INTO CORES_BANDEIRA VALUES('Branco','BR');
--CANADA
INSERT INTO CORES_BANDEIRA VALUES('Vermelho','CA');
INSERT INTO CORES_BANDEIRA VALUES('Branco','CA');
--SUICA
INSERT INTO CORES_BANDEIRA VALUES('Vermelho','CH');
INSERT INTO CORES_BANDEIRA VALUES('Branco','CH');
--CHINA
INSERT INTO CORES_BANDEIRA VALUES('Vermelho','CN');
INSERT INTO CORES_BANDEIRA VALUES('Amarelo','CN');
--ALEMANHA
INSERT INTO CORES_BANDEIRA VALUES('Preto','DE');
INSERT INTO CORES_BANDEIRA VALUES('Vermelho','DE');
INSERT INTO CORES_BANDEIRA VALUES('Ouro','DE');
--EGITO
INSERT INTO CORES_BANDEIRA VALUES('Vermelho','EG');
INSERT INTO CORES_BANDEIRA VALUES('Branco','EG');
INSERT INTO CORES_BANDEIRA VALUES('Preto','EG');
--FRANÇA
INSERT INTO CORES_BANDEIRA VALUES('Azul','FR');
INSERT INTO CORES_BANDEIRA VALUES('Branco','FR');
INSERT INTO CORES_BANDEIRA VALUES('Vermelho','FR');
--JAPÃO
INSERT INTO CORES_BANDEIRA VALUES('Branco','JP');
INSERT INTO CORES_BANDEIRA VALUES('Vermelho','JP');
--REINO UNIDO
INSERT INTO CORES_BANDEIRA VALUES('Vermelho','UK');
INSERT INTO CORES_BANDEIRA VALUES('Branco','UK');
INSERT INTO CORES_BANDEIRA VALUES('Azul','UK');
--ESTADOS UNIDOS
INSERT INTO CORES_BANDEIRA VALUES('Vermelho','US');
INSERT INTO CORES_BANDEIRA VALUES('Branco','US');
INSERT INTO CORES_BANDEIRA VALUES('Azul','US');


--TERRITORIO ANTARTIDA


INSERT INTO TERRITORIO_ANTARTIDA VALUES('BR',24524, 10000);
INSERT INTO TERRITORIO_ANTARTIDA VALUES('FR',14543, 22000);
INSERT INTO TERRITORIO_ANTARTIDA VALUES('CA',87346, 12000);
INSERT INTO TERRITORIO_ANTARTIDA VALUES('US',42362, 122000);
INSERT INTO TERRITORIO_ANTARTIDA VALUES('JP',39751, 43000);
INSERT INTO TERRITORIO_ANTARTIDA VALUES('CN',73653, 67850);




--CIDADE

INSERT INTO CIDADE VALUES ('CBR','CAMBERRA', 1, 'AU');
INSERT INTO CIDADE VALUES ('SYD','SYDNEY', 0, 'AU');


INSERT INTO CIDADE VALUES ('BSB','BRASILIA', 1, 'BR');
INSERT INTO CIDADE VALUES ('SP','SÃO PAULO', 0, 'BR');
INSERT INTO CIDADE VALUES ('REC','RECIFE', 0, 'BR');




INSERT INTO CIDADE VALUES ('OTT','OTTAWA', 1, 'CA');
INSERT INTO CIDADE VALUES ('TOR','TORONTO', 0, 'CA');


INSERT INTO CIDADE VALUES ('BER','BERNA', 1, 'CH');
INSERT INTO CIDADE VALUES ('GEN','GENEBRA', 0, 'CH');


INSERT INTO CIDADE VALUES ('PEK','PEQUIM', 1, 'CN');
INSERT INTO CIDADE VALUES ('SHA','SHANGHAI', 0, 'CN');


INSERT INTO CIDADE VALUES ('BLN','BERLIN', 1, 'DE');
INSERT INTO CIDADE VALUES ('MUN','MUNIQUE', 0, 'DE');


INSERT INTO CIDADE VALUES ('CAI','CAIRO', 1, 'EG');
INSERT INTO CIDADE VALUES ('ALE','ALEXANDRIA', 0, 'EG');


INSERT INTO CIDADE VALUES ('PAR','PARIS', 1, 'FR');
INSERT INTO CIDADE VALUES ('MRS','MARSELHA', 0, 'FR');


INSERT INTO CIDADE VALUES ('TYO','TOKYO', 1, 'JP');
INSERT INTO CIDADE VALUES ('OSA','OSAKA', 0, 'JP');


INSERT INTO CIDADE VALUES ('LON','LONDRES', 1, 'UK');
INSERT INTO CIDADE VALUES ('MAN','MANCHESTER', 0, 'UK');


INSERT INTO CIDADE VALUES ('WDC','WASHINGTON D.C', 1, 'US');
INSERT INTO CIDADE VALUES ('NYC','NOVA YORK', 0, 'US');


--IDIOMA: 


INSERT INTO IDIOMA VALUES('AR','ÁRABE', 274);
INSERT INTO IDIOMA VALUES('EN','INGLÊS', 1300); 
INSERT INTO IDIOMA VALUES('MND','MANDARIM', 1120);
INSERT INTO IDIOMA VALUES('ES','ESPANHOL', 600);
INSERT INTO IDIOMA VALUES('PT','PORTUGUÊS', 300);
INSERT INTO IDIOMA VALUES('FR','FRANCÊS', 267);
INSERT INTO IDIOMA VALUES('RU','RUSSO', 258);
INSERT INTO IDIOMA VALUES('ALE','ALEMÃO', 135);
INSERT INTO IDIOMA VALUES('JP', 'JAPONÊS',126);
INSERT INTO IDIOMA VALUES('IT','ITALIANO', 68);


--OFICIAL


INSERT INTO OFICIAL VALUES('BR','PT');
INSERT INTO OFICIAL VALUES('UK','EN');
INSERT INTO OFICIAL VALUES('CA','EN');
INSERT INTO OFICIAL VALUES('CA','FR');
INSERT INTO OFICIAL VALUES('AU','EN');
INSERT INTO OFICIAL VALUES('CH','FR');
INSERT INTO OFICIAL VALUES('CH','ALE');
INSERT INTO OFICIAL VALUES('JP','JP');
INSERT INTO OFICIAL VALUES('DE','ALE');
INSERT INTO OFICIAL VALUES('CN','MND');
INSERT INTO OFICIAL VALUES('EG','AR');
INSERT INTO OFICIAL VALUES('FR','FR');




--OBRA:


INSERT INTO OBRA_PUBLICA VALUES('HIDR-ITAIPU-84', 17600);
INSERT INTO OBRA_PUBLICA VALUES('HIDR-3GARGANTAS-94', 40000);


--REALIZA:
INSERT INTO REALIZA VALUES('HIDR-ITAIPU-84', 'BR');
INSERT INTO REALIZA VALUES('HIDR-3GARGANTAS-94', 'CN');
INSERT INTO REALIZA VALUES('HIDR-3GARGANTAS-94', 'JP');




--EMPRESA PRIVADA: 
INSERT INTO EMPRESA_PRIVADA VALUES('ODEBRECHT','BR167280-22','OSCAR FREIRE', 'PINHEIROS','SP');
INSERT INTO EMPRESA_PRIVADA VALUES('EVERGRANDE','CN093756-12','NANLU HWI', 'HUIJIAOCUN','SHA');
INSERT INTO EMPRESA_PRIVADA VALUES(‘EMPRESAMASSA’,'BR182937-09','AGAMENOM', ‘DERBY’,'REC');




--PARCERIA:
INSERT INTO PARCERIA VALUES('BR', 'HIDR-ITAIPU-84', 'BR167280-22');
INSERT INTO PARCERIA VALUES('CN', 'HIDR-3GARGANTAS-94', 'CN093756-12');
INSERT INTO PARCERIA VALUES('JP', 'HIDR-3GARGANTAS-94', 'CN093756-12');




--COMMODITY:


INSERT INTO COMMODITY VALUES(1201, 28, 'SOJA EM GRÃOS');
INSERT INTO COMMODITY VALUES(2601, 120, 'FERRO');
--COMPRAS:
INSERT INTO COMPROU VALUES(1201,'USD','US', TO_DATE('17/12/2015', 'DD/MM/YYYY') , 28280);
INSERT INTO COMPROU VALUES(1201,'USD','US', TO_DATE('17/08/2016', 'DD/MM/YYYY') , 2366);
INSERT INTO COMPROU VALUES(1201,'CNY','CN', TO_DATE('03/01/2016', 'DD/MM/YYYY') , 5625);
INSERT INTO COMPROU VALUES(2601,'USD','JP', TO_DATE('15/10/2002', 'DD/MM/YYYY') , 36000);
INSERT INTO COMPROU VALUES(2601,'USD','CA', TO_DATE('21/07/2022', 'DD/MM/YYYY') , 4800);